### ISSUE TITLE
json.SyntaxError when using GetSearch

### ISSUE THREAD

**Issue by moussetc** [sanzaru/go-giphy#1]
Hi,
The following test fails:
```
func Test(t *testing.T) {
	giphy := libgiphy.NewGiphy(PUBLIC_BETA_API_KEY) 
	response, err := giphy.GetSearch("hello", 10, 0, "", "", false)
	assert.Nil(t, err)
}
```
with the following output:
> --- FAIL: Test (0.04s)
> 	assertions.go:247: 
> 	Error Trace:	gifProvider_test.go:43
> 	Error:      	Expected nil, but got: &json.SyntaxError{msg:"unexpected end of JSON input", Offset:0}

I am, however, using getTranslate without issue.
Thank you for your work!

**Comment by sanzaru** [comment]
Thanks for reporting. There was an error converting the parameters for the search. Should be fixed now, so that your test passes.

**Comment by moussetc** [comment]
It works fine now. Thank you for the extremely quick fix! :)
